name: retail_finance
version: '1.0.0'
require-dbt-version: [">=1.9.0"]

profile: retail_demo

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  retail_finance:
    +materialized: table
    +schema: finance
