name: harmony_finance
version: '1.0.0'

profile: harmony_finance

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  harmony_finance:
    +materialized: table
    +schema: finance
