name: harmony_central_data
version: '1.0.0'

profile: harmony_central_data

model-paths:    ["models"]
seed-paths:     ["seeds"]
test-paths:     ["tests"]
macro-paths:    ["macros"]
analysis-paths: ["analyses"]
snapshot-paths: ["snapshots"]

target-path:   "target"
clean-targets: ["target", "dbt_packages"]

vars:
  retail_database: HICHAMB_FIVETRAN_DEMO
  retail_schema:   RETAIL_DEMO_RETAIL

seeds:
  harmony_central_data:
    +schema: seeds

models:
  harmony_central_data:
    staging:
      +materialized: view
      +schema: staging

    intermediate:
      +materialized: ephemeral

    marts:
      core:
        +materialized: table
        +schema: marts
        +persist_docs:
          relation: true
          columns: true
      finance:
        +materialized: table
        +schema: marts
        +persist_docs:
          relation: true
          columns: true

    semantic:
      +materialized: table
      +schema: semantic
