-- =============================================================================
-- Fretwork Guitars: Snowflake Infrastructure Setup
-- Run this once as ACCOUNTADMIN (or SYSADMIN + SECURITYADMIN)
-- =============================================================================

USE ROLE SYSADMIN;

-- -----------------------------------------------------------------------------
-- Warehouse
-- -----------------------------------------------------------------------------
CREATE WAREHOUSE IF NOT EXISTS FRETWORK_WH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND   = 60
    AUTO_RESUME    = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Fretwork Guitars demo warehouse';

-- -----------------------------------------------------------------------------
-- Database + Schemas
-- -----------------------------------------------------------------------------
CREATE DATABASE IF NOT EXISTS FRETWORK_GUITARS
    COMMENT = 'Fretwork Guitars demo database';

USE DATABASE FRETWORK_GUITARS;

-- Raw ingestion schemas (Fivetran writes here)
CREATE SCHEMA IF NOT EXISTS RAW_SHOPIFY  COMMENT = 'Fivetran Shopify connector raw tables';
CREATE SCHEMA IF NOT EXISTS RAW_STRIPE   COMMENT = 'Fivetran Stripe connector raw tables';

-- dbt transformation schemas (dbt writes here)
CREATE SCHEMA IF NOT EXISTS STAGING         COMMENT = 'dbt staging views';
CREATE SCHEMA IF NOT EXISTS SHOPIFY_STAGING COMMENT = 'Fivetran dbt_shopify_source staging views';
CREATE SCHEMA IF NOT EXISTS STRIPE_STAGING  COMMENT = 'Fivetran dbt_stripe_source staging views';
CREATE SCHEMA IF NOT EXISTS SHOPIFY_MART    COMMENT = 'Fivetran dbt_shopify mart models';
CREATE SCHEMA IF NOT EXISTS STRIPE_MART     COMMENT = 'Fivetran dbt_stripe mart models';
CREATE SCHEMA IF NOT EXISTS INTERMEDIATE    COMMENT = 'dbt intermediate (ephemeral, mostly invisible)';
CREATE SCHEMA IF NOT EXISTS MARTS           COMMENT = 'dbt core + finance mart tables';
CREATE SCHEMA IF NOT EXISTS SEMANTIC        COMMENT = 'dbt semantic layer views + time spine';

-- -----------------------------------------------------------------------------
-- Roles
-- -----------------------------------------------------------------------------
USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS FRETWORK_TRANSFORMER
    COMMENT = 'Role for dbt transformations (CI/CD + dbt Cloud)';

CREATE ROLE IF NOT EXISTS FRETWORK_ANALYST
    COMMENT = 'Role for BI tools, Cortex Analyst, Streamlit app';

CREATE ROLE IF NOT EXISTS FRETWORK_FIVETRAN
    COMMENT = 'Role for Fivetran connector service account';

-- Grant role hierarchy
GRANT ROLE FRETWORK_TRANSFORMER TO ROLE SYSADMIN;
GRANT ROLE FRETWORK_ANALYST     TO ROLE SYSADMIN;
GRANT ROLE FRETWORK_FIVETRAN    TO ROLE SYSADMIN;

-- -----------------------------------------------------------------------------
-- Warehouse grants
-- -----------------------------------------------------------------------------
GRANT USAGE ON WAREHOUSE FRETWORK_WH TO ROLE FRETWORK_TRANSFORMER;
GRANT USAGE ON WAREHOUSE FRETWORK_WH TO ROLE FRETWORK_ANALYST;
GRANT USAGE ON WAREHOUSE FRETWORK_WH TO ROLE FRETWORK_FIVETRAN;

-- -----------------------------------------------------------------------------
-- Database + Schema grants: TRANSFORMER (dbt)
-- Can read raw, write to all dbt schemas
-- -----------------------------------------------------------------------------
GRANT USAGE  ON DATABASE FRETWORK_GUITARS TO ROLE FRETWORK_TRANSFORMER;
GRANT USAGE  ON ALL SCHEMAS IN DATABASE FRETWORK_GUITARS TO ROLE FRETWORK_TRANSFORMER;

-- Read raw ingestion schemas
GRANT SELECT ON ALL TABLES IN SCHEMA FRETWORK_GUITARS.RAW_SHOPIFY TO ROLE FRETWORK_TRANSFORMER;
GRANT SELECT ON ALL TABLES IN SCHEMA FRETWORK_GUITARS.RAW_STRIPE  TO ROLE FRETWORK_TRANSFORMER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA FRETWORK_GUITARS.RAW_SHOPIFY TO ROLE FRETWORK_TRANSFORMER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA FRETWORK_GUITARS.RAW_STRIPE  TO ROLE FRETWORK_TRANSFORMER;

-- Write to dbt output schemas
GRANT ALL PRIVILEGES ON SCHEMA FRETWORK_GUITARS.STAGING          TO ROLE FRETWORK_TRANSFORMER;
GRANT ALL PRIVILEGES ON SCHEMA FRETWORK_GUITARS.SHOPIFY_STAGING   TO ROLE FRETWORK_TRANSFORMER;
GRANT ALL PRIVILEGES ON SCHEMA FRETWORK_GUITARS.STRIPE_STAGING    TO ROLE FRETWORK_TRANSFORMER;
GRANT ALL PRIVILEGES ON SCHEMA FRETWORK_GUITARS.SHOPIFY_MART      TO ROLE FRETWORK_TRANSFORMER;
GRANT ALL PRIVILEGES ON SCHEMA FRETWORK_GUITARS.STRIPE_MART       TO ROLE FRETWORK_TRANSFORMER;
GRANT ALL PRIVILEGES ON SCHEMA FRETWORK_GUITARS.MARTS             TO ROLE FRETWORK_TRANSFORMER;
GRANT ALL PRIVILEGES ON SCHEMA FRETWORK_GUITARS.SEMANTIC          TO ROLE FRETWORK_TRANSFORMER;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA FRETWORK_GUITARS.MARTS    TO ROLE FRETWORK_TRANSFORMER;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA FRETWORK_GUITARS.MARTS TO ROLE FRETWORK_TRANSFORMER;

-- -----------------------------------------------------------------------------
-- Database + Schema grants: ANALYST (BI, Cortex, Streamlit)
-- Read access to marts and semantic layer
-- -----------------------------------------------------------------------------
GRANT USAGE  ON DATABASE FRETWORK_GUITARS TO ROLE FRETWORK_ANALYST;
GRANT USAGE  ON SCHEMA FRETWORK_GUITARS.MARTS       TO ROLE FRETWORK_ANALYST;
GRANT USAGE  ON SCHEMA FRETWORK_GUITARS.SEMANTIC     TO ROLE FRETWORK_ANALYST;
GRANT USAGE  ON SCHEMA FRETWORK_GUITARS.SHOPIFY_MART TO ROLE FRETWORK_ANALYST;
GRANT USAGE  ON SCHEMA FRETWORK_GUITARS.STRIPE_MART  TO ROLE FRETWORK_ANALYST;

-- Also read raw schemas for the "Act 1 - chaos" demo
GRANT USAGE  ON SCHEMA FRETWORK_GUITARS.RAW_SHOPIFY TO ROLE FRETWORK_ANALYST;
GRANT USAGE  ON SCHEMA FRETWORK_GUITARS.RAW_STRIPE  TO ROLE FRETWORK_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA FRETWORK_GUITARS.RAW_SHOPIFY TO ROLE FRETWORK_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA FRETWORK_GUITARS.RAW_STRIPE  TO ROLE FRETWORK_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA FRETWORK_GUITARS.RAW_SHOPIFY TO ROLE FRETWORK_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA FRETWORK_GUITARS.RAW_STRIPE  TO ROLE FRETWORK_ANALYST;

GRANT SELECT ON ALL TABLES IN SCHEMA FRETWORK_GUITARS.MARTS    TO ROLE FRETWORK_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA FRETWORK_GUITARS.MARTS TO ROLE FRETWORK_ANALYST;
GRANT SELECT ON ALL VIEWS IN SCHEMA FRETWORK_GUITARS.SEMANTIC  TO ROLE FRETWORK_ANALYST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA FRETWORK_GUITARS.SEMANTIC TO ROLE FRETWORK_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA FRETWORK_GUITARS.SHOPIFY_MART TO ROLE FRETWORK_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA FRETWORK_GUITARS.SHOPIFY_MART TO ROLE FRETWORK_ANALYST;

-- Cortex Analyst requires SNOWFLAKE.CORTEX_USER privilege
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE FRETWORK_ANALYST;

-- -----------------------------------------------------------------------------
-- Database + Schema grants: FIVETRAN (connector service account)
-- -----------------------------------------------------------------------------
GRANT USAGE ON DATABASE FRETWORK_GUITARS TO ROLE FRETWORK_FIVETRAN;
GRANT USAGE, CREATE TABLE ON SCHEMA FRETWORK_GUITARS.RAW_SHOPIFY TO ROLE FRETWORK_FIVETRAN;
GRANT USAGE, CREATE TABLE ON SCHEMA FRETWORK_GUITARS.RAW_STRIPE  TO ROLE FRETWORK_FIVETRAN;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA FRETWORK_GUITARS.RAW_SHOPIFY TO ROLE FRETWORK_FIVETRAN;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA FRETWORK_GUITARS.RAW_STRIPE  TO ROLE FRETWORK_FIVETRAN;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA FRETWORK_GUITARS.RAW_SHOPIFY TO ROLE FRETWORK_FIVETRAN;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA FRETWORK_GUITARS.RAW_STRIPE  TO ROLE FRETWORK_FIVETRAN;

-- -----------------------------------------------------------------------------
-- Assign roles to users (replace with your actual usernames)
-- -----------------------------------------------------------------------------
-- GRANT ROLE FRETWORK_TRANSFORMER TO USER <dbt_service_account_user>;
-- GRANT ROLE FRETWORK_ANALYST     TO USER <your_snowflake_username>;
-- GRANT ROLE FRETWORK_FIVETRAN    TO USER <fivetran_service_account_user>;
